### ISSUE TITLE
Write the internal code for R functions

### ISSUE THREAD

**Issue by kmoravej** [UBC-MDS/labzenr#14]
After writing your unit tests, write the internal code for your R functions.

Write function code and tests in close temporal proximity with each other. The process of writing function code and test cases will be iterative; there will be several rounds of writing tests → function improvement → writing more tests → function improvement → writing more tests → function improvement, etc.

Make sure that the tests cover all branches (e.g., if your function has an if statement, you should have tests where the if statement is true, and where the if statement is false.

**Comment by rtaph** [comment]
Done:

- @kmoravej contributed code for parse_lab() and check_repo_link(), as well as tests for parse_lab().
- @sukh2929 contributed code for check_lat_version() and check_commits() and test for repo_link()
- @rtaph contributed code for extract_points() and count_points() and wrote unit tests for both.
