### ISSUE TITLE
update code documentation

### ISSUE THREAD

**Issue by kmoravej** [UBC-MDS/labzenr#15]
As you develop your code and test cases, update your code documentation so that it makes sense with any of the changes you have made. Do not forget to also document your test functions.

**Comment by rtaph** [comment]
Done. All function have roxygen code blocks for which .Rd files have been generated. Where appropriate, we have used `@InheritParams` to DRY out our documentation and reduce the risk of duplication.

Test functions are commented where necessary and have informative assertion messages.
