### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by kmoravej** [UBC-MDS/labzenr#16]
The function should be written defensively. That is, it should handle incorrect input and errors detected during execution via throwing exceptions with useful error messages, and there should be tests to confirm that the exceptions result in the expected behaviour of the function.

**Comment by rtaph** [comment]
- parse_lab() check defensively for bad inputs.
- extract_points() checks the rubrics for parsing consistency. 
- check_commits() checks defensively that you are on the main/master branch.
