### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kmoravej** [UBC-MDS/labzenr#28]
Your package documentation should be very clear by the end of this milestone. To do this, you should use vignette package-wide documentation in R, as well as the pkgdown R package to set up a website for your package. In doing this make sure you:

- include a full usage demonstration of all your package functions (this means a runnable example - give them data!) in your vignette

- include installation instructions in the README.Rmd file

- examine Roxygen2 documentation of your functions to make sure it is clear

**Comment by sukh2929** [comment]
Documentation complete
