### ISSUE TITLE
Pick License 

### ISSUE THREAD

**Issue by kmoravej** [UBC-MDS/labzenr#29]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly dicussed.

**Comment by sukh2929** [comment]
It seems to me that we can use :
 MIT - accessible to anyone 
 Hippocratic licence - for compliance with Human Rights Principles

**Comment by kmoravej** [comment]
MIT seems fine. It  allows the users to modify and improve the code. However, the `labzen` is mainly beneficial to the MDS students. The next cohorts can build and improve the package if they find it useful. 

It also has the following limitations:
- Liability
- Warranty 

So, we would not be responsible for any harm, or bug that the package may cause.

**Comment by rtaph** [comment]
My preference would be to stick with the MIT license. It is permissive and I would say we want users to have a high degree of freedom in using and repackaging this package.

Here are the licenses of our dependencies:


|Package     |License                                     |
|:-----------|:-------------------------------------------|
|utf8        |Apache License (== 2.0) &#124; file LICENSE |
|yaml        |BSD_3_clause + file LICENSE                 |
|zip         |CC0                                         |
|stringi     |file LICENSE                                |
|mime        |GPL                                         |
|digest      |GPL (>= 2)                                  |
|fansi       |GPL (>= 2)                                  |
|lubridate   |GPL (>= 2)                                  |
|Rcpp        |GPL (>= 2)                                  |
|stringr     |GPL-2 &#124; file LICENSE                   |
|assertthat  |GPL-3                                       |
|clipr       |GPL-3                                       |
|ellipsis    |GPL-3                                       |
|fs          |GPL-3                                       |
|ini         |GPL-3                                       |
|snakecase   |GPL-3                                       |
|tidyselect  |GPL-3                                       |
|whisker     |GPL-3                                       |
|purrr       |GPL-3 &#124; file LICENSE                   |
|askpass     |MIT + file LICENSE                          |
|cli         |MIT + file LICENSE                          |
|cpp11       |MIT + file LICENSE                          |
|crayon      |MIT + file LICENSE                          |
|credentials |MIT + file LICENSE                          |
|curl        |MIT + file LICENSE                          |
|desc        |MIT + file LICENSE                          |
|dplyr       |MIT + file LICENSE                          |
|generics    |MIT + file LICENSE                          |
|gert        |MIT + file LICENSE                          |
|gh          |MIT + file LICENSE                          |
|gitcreds    |MIT + file LICENSE                          |
|glue        |MIT + file LICENSE                          |
|httr        |MIT + file LICENSE                          |
|janitor     |MIT + file LICENSE                          |
|jsonlite    |MIT + file LICENSE                          |
|lifecycle   |MIT + file LICENSE                          |
|magrittr    |MIT + file LICENSE                          |
|openssl     |MIT + file LICENSE                          |
|pillar      |MIT + file LICENSE                          |
|pkgconfig   |MIT + file LICENSE                          |
|R6          |MIT + file LICENSE                          |
|rappdirs    |MIT + file LICENSE                          |
|rlang       |MIT + file LICENSE                          |
|rprojroot   |MIT + file LICENSE                          |
|rstudioapi  |MIT + file LICENSE                          |
|sys         |MIT + file LICENSE                          |
|tibble      |MIT + file LICENSE                          |
|tidyr       |MIT + file LICENSE                          |
|usethis     |MIT + file LICENSE                          |
|vctrs       |MIT + file LICENSE                          |
|withr       |MIT + file LICENSE                          |
